language: node_js
node_js:
  - '12'
script:
  - npm run lint
  - npm test
  - npm run build:react
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
  local_dir: build
